version: "3"

networks:
  app-network:
    driver: bridge

services:
  app:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - manager
    ports:
      - "8080:8080"

  manager:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile

  worker:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - manager

